FROM r30min

## Install packages that Stan and R packages require
RUN apt-get install -y libtbb2 libxt-dev

## Install R Packages without specifying their versions
RUN Rscript -e 'remotes::install_version("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))'
RUN Rscript -e 'remotes::install_version("posterior")'
RUN Rscript -e 'remotes::install_version("bayesplot")'

## Create a mount point
ARG R_USERNAME=rstudio
USER "${R_USERNAME}"

RUN mkdir -p "/home/${R_USERNAME}/work"
RUN Rscript -e 'cmdstanr::install_cmdstan()'

ARG R_USER_GROUP_NAME="${R_USERNAME}:${R_USERNAME}"
ARG TARGET_DIR="/home/${R_USERNAME}/Rin30minutes/"
COPY stan_example.Rmd "${TARGET_DIR}/"
COPY mixture_normals.stan "${TARGET_DIR}/"

USER root
